# Generated by Django 4.2.3 on 2023-08-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_alter_column_board_alter_subtask_supertask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='supertask',
            new_name='task',
        ),
    ]
